// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrx7k8tcnmVEeJyWdv9dzrmavfEY2Ndo',
    appId: '1:432183058187:web:1112cebbd0527fc104cc0e',
    messagingSenderId: '432183058187',
    projectId: 'kakuro-insa',
    authDomain: 'kakuro-insa.firebaseapp.com',
    storageBucket: 'kakuro-insa.appspot.com',
    measurementId: 'G-XYR2C10XEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBRChQfuqZzCuqvAEwqtxxFfCA2pZcSkQ',
    appId: '1:432183058187:android:784b7587c2c2dd4d04cc0e',
    messagingSenderId: '432183058187',
    projectId: 'kakuro-insa',
    storageBucket: 'kakuro-insa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5GNI2RfoDj3Y9qHp0eQuevABeAtnAu2g',
    appId: '1:432183058187:ios:1dd4de3250b1f53e04cc0e',
    messagingSenderId: '432183058187',
    projectId: 'kakuro-insa',
    storageBucket: 'kakuro-insa.appspot.com',
    androidClientId:
        '432183058187-gcfpcp0f7qh8100o7pcpnpp933tqmjr4.apps.googleusercontent.com',
    iosClientId:
        '432183058187-p8ul9hbijgk4glr7lrm2lq6r7vh7g25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5GNI2RfoDj3Y9qHp0eQuevABeAtnAu2g',
    appId: '1:432183058187:ios:1dd4de3250b1f53e04cc0e',
    messagingSenderId: '432183058187',
    projectId: 'kakuro-insa',
    storageBucket: 'kakuro-insa.appspot.com',
    androidClientId:
        '432183058187-gcfpcp0f7qh8100o7pcpnpp933tqmjr4.apps.googleusercontent.com',
    iosClientId:
        '432183058187-p8ul9hbijgk4glr7lrm2lq6r7vh7g25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakuro',
  );
}
